### ISSUE TITLE
use binaries for strings?

### ISSUE THREAD

**Issue by yrashk** [beamjs/erlv8#59]
(08:45) <   etrepum> that's probably something we would do if we were going to use something like this, lists take up too much RAM (especially on 64-bit)

**Comment by yrashk** [comment]
now we at least accept iolists in a leue of string lists

**Comment by foobarto** [comment]
I would say definitely use binaries instead of lists wherever possible

**Comment by yrashk** [comment]
erlv8 will return binaries for JavaScript strings now
