### ISSUE TITLE
Can't get error details from exception

### ISSUE THREAD

**Issue by lyxsus** [beamjs/erlv8#66]
Following wiki instruction gives me empty list, when detailed exception info is expected:

Example:

1> {ok, VM} = erlv8_vm:start().
{ok,<0.548.0>}
2> erlv8_vm:run(VM,"f = function (x) { return x \* 10 }; f(10)").
{ok,100}
3> {Resolution, Value} = erlv8_vm:run(VM,"f = function (x) { return x \* 10 }; f(10").
{throw,{erlv8_object,<<>>,<0.548.0>}}
4> Value:proplist().
[]

Instead of:

…
4> Value:proplist ().
[{"message","Unexpected end of input"},
 {"stack","SyntaxError: Unexpected end of input"},
 {"type","unexpected_eos"},
 {"arguments",[]},
 {"name","SyntaxError"}]

Maybe, I should recompile v8? It's macos builded as rebar dep.

**Comment by yrashk** [comment]
Will look into this next week or sooner (about to take off for a
trip). Make sure everything is compiled from scratch.

On Tue, Nov 29, 2011 at 8:26 PM, lyxsus
reply@reply.github.com
wrote:

**Comment by yrashk** [comment]
@lyxsus interesting

``` erlang
3>  {Resolution, Value} = erlv8_vm:run(VM,"f = function (x) { return x * 10 }; f(10").
{throw,{erlv8_object,<<>>,<0.38.0>}}
4> Value:proplist().
[]
%% but
5> Value:get_value("message").
<<"Unexpected end of input">>
```

Will look into this. Not sure what happened.

**Comment by yrashk** [comment]
What's even more interesting:

``` erlang
8>  f(Resolution), f(Value), {Resolution, Value} = erlv8_vm:run(VM,"throw ({a:1,b:2})").                       
{throw,{erlv8_object,<<>>,<0.38.0>}}
9> Value:proplist().                                                                    
[{<<"a">>,1},{<<"b">>,2}]
```
