### ISSUE TITLE
failing test case

### ISSUE THREAD

**Issue by Licenser** [beamjs/erlv8#69]
The failing test is caused by a erlang bug as exampled here it won't be fixed in erlv8:

https://github.com/Licenser/erlniftest

**Comment by yrashk** [comment]
Can we consider sending a patch to the OTP team?

**Comment by Licenser** [comment]
I was told it isn't really a bug in erlang but it just don't supports UTF8 at the moment :) so now I am investigating a way around it but I'm not exactly sure in which place things break down any more (erlang -(1)-> js -(2)-> erlang)

since I am not sure how to explore the stwo places I just see what is before 1 and after 2

**Comment by yrashk** [comment]
Allegedly fixed by #70
