### ISSUE TITLE
make on debian

### ISSUE THREAD

**Issue by undassa** [beamjs/erlv8#73]
==> erlv8 (compile)
src/erlv8_nif.erl:32: function error/1 undefined
src/erlv8_nif.erl:35: function error/1 undefined
src/erlv8_nif.erl:38: function error/1 undefined
src/erlv8_nif.erl:41: function error/1 undefined
src/erlv8_nif.erl:44: function error/1 undefined
src/erlv8_nif.erl:47: function error/1 undefined
src/erlv8_nif.erl:50: function error/1 undefined
make: **\* [compile] Error 1

**Comment by yrashk** [comment]
I suspect old Erlang version. What's the version of Erlang used?

**Comment by undassa** [comment]
thx for fast reply )
Erlang R14A (erts-5.8) [source] [64-bit]

**Comment by yrashk** [comment]
That's likely the issue. This is a pretty damn old _alpha_ version. Try
R15B+

On Mon, Nov 5, 2012 at 1:06 PM, Alexander Kaloshin <notifications@github.com

**Comment by undassa** [comment]
Oh.. debian... thx. If ok - close ticket.

**Comment by undassa** [comment]
Yeap. it's ok on 15B02.
