### ISSUE TITLE
Why Erlang 'ok' is translated to JS true?

### ISSUE THREAD

**Issue by gleber** [beamjs/erlv8#74]
Why Erlang 'ok' is translated to JS true? What are the reasons for this? I find it a bit inconsistent.

**Comment by yrashk** [comment]
Good question. I don't remember anything about that...need to dig through the logs to see if there are any traces of why decision has been made.

**Comment by yrashk** [comment]
https://github.com/beamjs/erlv8/commit/6cd5d23650e10e79a9995a9b823e91b7a76b4b83 but no motivation was recorded. Is it causing some problems or just hurts your sense of beautiful?

**Comment by gleber** [comment]
The latter :) I am a proponent of as tight as possible specifications with as little ambiguousness as possible, hence in my opinion it is a suboptimal choice. I'll let you know if it creates real-life problems for me.

**Comment by yrashk** [comment]
Gotcha. I would rather keep this because I don't know whether anybody relies on this behaviour or not (or at most, go through a deprecation procedure). Closing the issue for now.

I am pretty sure there was a use case for this. But after 2 years, I can't remember it. Sorry!
